packageExtensions:
  "@octokit/rest@*":
    dependencies:
      "@octokit/core": "*"
  "@testing-library/user-event@*":
    dependencies:
      "@testing-library/dom": "*"
  eslint-config-react-app@*:
    dependencies:
      babel-eslint: "*"
  eslint-plugin-prettier@*:
    dependencies:
      prettier: "*"
  focus-trap-react@*:
    dependencies:
      prop-types: "*"
  jest-styled-components@*:
    dependencies:
      react: "*"
      react-dom: "*"
      styled-components: "*"
  middie@*:
    dependencies:
      fastify: "*"
  react-dev-utils@*:
    dependencies:
      typescript: "*"
      webpack: "*"
  react-idle-timer@*:
    dependencies:
      "@babel/runtime": "*"
      prop-types: "*"
  react-redux-toastr@*:
    dependencies:
      react: "*"
  react-scripts@*:
    dependencies:
      eslint-plugin-prettier: "*"
  sass-loader@*:
    dependencies:
      sass: "*"
      webpack: "*"
  semantic-ui-react@*:
    dependencies:
      react: "*"
      react-dom: "*"
  styled-components@*:
    dependencies:
      react-is: "*"
  swagger-express-ts@*:
    dependencies:
      lodash: "*"
  ts-jest@*:
    dependencies:
      jest: "*"
  "@storybook/builder-webpack4@*":
    dependencies:
      sass: "*"
      sass-loader: "*"
      svg-inline-loader: "*"
  "@storybook/core-server@*":
    dependencies:
      "@storybook/manager-webpack5": "*"


plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpMode: strict

yarnPath: .yarn/releases/yarn-3.0.0.cjs
