name: lib-components

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/lib-components.yaml'
      - 'packages/frontend/lib-components/**'
      - 'packages/frontend/lib-utils/**'

  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/lib-components.yaml'
      - 'packages/frontend/lib-components/**'
      - 'packages/frontend/lib-utils/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Run linter
        run: yarn workspace lib-components lint
      - name: Run build
        run: yarn workspace lib-components build
