name: lib-utils

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/lib-utils.yaml'
      - 'packages/frontend/lib-utils/**'

  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/lib-utils.yaml'
      - 'packages/frontend/lib-utils/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Run linter
        run: yarn workspace lib-utils lint
